"""Update facility dogs cascade delete all

Revision ID: 0d303998daa5
Revises: a2d65b445251
Create Date: 2023-09-06 18:57:11.372086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d303998daa5'
down_revision: Union[str, None] = 'a2d65b445251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###