"""Rename table adopter first name

Revision ID: a2d65b445251
Revises: c7b94ff594a8
Create Date: 2023-09-06 15:40:05.352364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d65b445251'
down_revision: Union[str, None] = 'c7b94ff594a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adopters', sa.Column('first_name', sa.String(), nullable=False))
    op.drop_column('adopters', 'fisrt_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adopters', sa.Column('fisrt_name', sa.VARCHAR(), nullable=False))
    op.drop_column('adopters', 'first_name')
    # ### end Alembic commands ###